### ISSUE TITLE
Feature Request - upgrade Laravel to latest version

### ISSUE THREAD

**Issue by k-zakhariy** [matthiku/cSpot#196]

**Comment by matthiku** [comment]
### Step 1: Upgrade to Laravel 5.4
instructions see: https://laravel.com/docs/5.4/upgrade#upgrade-5.4.0
- upgrade _composer.json_, then `composer update`
- add tinker: `composer require laravel/tinker` then
- add `Laravel\Tinker\TinkerServiceProvider::class` to _app\config.php_
- run `php artisan view:clear`

**Comment by matthiku** [comment]
Production server also successfully upgraded to 5.4!

- needed also to delete  `/bootstrap/cache/compiled.php`

**Comment by matthiku** [comment]
## Upgrading to Laravel 5.5
upgrade guide see: https://laravel.com/docs/5.5/upgrade
- update _composer.json_
- run `composer update`

**Comment by matthiku** [comment]
## Upgrading to Laravel 5.6
