### ISSUE TITLE
Tooltips prevent direct button click on iPhones

### ISSUE THREAD

**Issue by matthiku** [matthiku/cSpot#31]
On an iPhone, the first touch just shows the tooltip and only the second tab executes the button action.

And it also doesn't work well on Android phones as it only can be seen briefly before the action is triggered.
![screenshot_2016-02-18-13-42-11](https://cloud.githubusercontent.com/assets/12457522/13145341/e9559ad0-d647-11e5-9330-bfb3bc8350f5.png)

-> Better use small (i) info buttons that can be clicked to provide the information

**Comment by manuelkuhs** [comment]
Agreed :)

Though I think technically it's not a bug?

**Comment by matthiku** [comment]
Yeah, you're right. It's just a feature! ;-) 

But well, I'm treating it as a bug since it doesn't behave as intended. Since I want to follow my 'mobile-first' approach, it doesn't work properly on either mobile platform.

**Comment by matthiku** [comment]
Preview of the solution:
![issue31](https://cloud.githubusercontent.com/assets/12457522/13145271/6b159080-d647-11e5-94a1-ef7a99ad3a6f.png)

**Comment by manuelkuhs** [comment]
Elegant!

Kind regards,
Manuel

On 18 February 2016 at 13:56:38, Matthias Kuhs (notifications@github.com) wrote:

Preview of the solution:

**Comment by matthiku** [comment]
@manuelkuhs Can you check if this is the same problem (tool tips prevent direct click of buttons) when you open a service plan (like for the next Sunday)?

**Comment by manuelkuhs** [comment]
Yes same issue!

Kind regards,
Manuel

**Comment by matthiku** [comment]
I leave this as-is for now, until I get more feedback.
